# Provides interview questions filtered by company and role.
from typing import Optional

from fastapi import APIRouter, Query

router = APIRouter()
QUESTIONS = [
    # Amazon
    {
        "id": "amz-1",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to meet a tight deadline and how you handled it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-2",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you failed or made a mistake. What did you learn and what would you do differently?",
        "timeLimit": 120,
    },
    {
        "id": "amz-3",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had a disagreement with your manager and how you handled it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-4",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you took on significant work outside your normal area of responsibility.",
        "timeLimit": 120,
    },
    {
        "id": "amz-5",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to make a decision with limited data.",
        "timeLimit": 120,
    },
    {
        "id": "amz-6",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you went above and beyond for a customer.",
        "timeLimit": 120,
    },
    {
        "id": "amz-7",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to deal with ambiguity.",
        "timeLimit": 120,
    },
    {
        "id": "amz-8",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you solved a complex problem and how you went about it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-9",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you pushed back on a decision made by senior leadership.",
        "timeLimit": 120,
    },
    {
        "id": "amz-10",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you took action on a project without waiting for your manager's approval.",
        "timeLimit": 120,
    },
    {
        "id": "amz-11",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about something you built end-to-end without relying on others.",
        "timeLimit": 120,
    },
    {
        "id": "amz-12",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had a disagreement with a colleague and how you resolved it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-13",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you took a calculated risk when speed was critical.",
        "timeLimit": 120,
    },
    {
        "id": "amz-14",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to make a difficult trade-off on a project.",
        "timeLimit": 120,
    },
    {
        "id": "amz-15",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you implemented an unpopular idea despite facing resistance.",
        "timeLimit": 120,
    },
    {
        "id": "amz-16",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you received negative or difficult feedback and how you handled it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-17",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to juggle multiple competing priorities or deadlines.",
        "timeLimit": 120,
    },
    {
        "id": "amz-18",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to dig deeper or ask more questions to get to the root cause of an issue.",
        "timeLimit": 120,
    },
    {
        "id": "amz-19",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to convince a disagreeing team to adopt your proposal.",
        "timeLimit": 120,
    },
    {
        "id": "amz-20",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you disagreed with a decision.",
        "timeLimit": 120,
    },
    {
        "id": "amz-21",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you proposed a simple or non-intuitive solution to a complex problem.",
        "timeLimit": 120,
    },
    {
        "id": "amz-22",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you faced an ambiguous situation and how you navigated it.",
        "timeLimit": 120,
    },
    {
        "id": "amz-23",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to cut corners to meet a deadline.",
        "timeLimit": 120,
    },
    {
        "id": "amz-24",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you failed to meet a commitment.",
        "timeLimit": 120,
    },
    {
        "id": "amz-25",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time one of your projects failed.",
        "timeLimit": 120,
    },
    {
        "id": "amz-26",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you missed a deadline.",
        "timeLimit": 120,
    },
    {
        "id": "amz-27",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to make a critical decision with many options and very little time.",
        "timeLimit": 120,
    },
    {
        "id": "amz-28",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to earn the trust of a team member or stakeholder.",
        "timeLimit": 120,
    },
    {
        "id": "amz-29",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to quickly learn a new skill or technology.",
        "timeLimit": 120,
    },
    {
        "id": "amz-30",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a technical decision you made and its impact on your project.",
        "timeLimit": 120,
    },
    {
        "id": "amz-31",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a technical challenge you have overcome in a recent project.",
        "timeLimit": 120,
    },
    {
        "id": "amz-32",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to deal with conflicting priorities from stakeholders and how you secured alignment.",
        "timeLimit": 120,
    },
    {
        "id": "amz-33",
        "company": "Amazon",
        "role": "product-manager",
        "question": "Tell me about a time you had to prioritize competing customer needs.",
        "timeLimit": 120,
    },
    {
        "id": "amz-34",
        "company": "Amazon",
        "role": "data-analyst",
        "question": "Tell me about a time your analysis changed a business decision.",
        "timeLimit": 120,
    },
    {
        "id": "amz-35",
        "company": "Amazon",
        "role": "data-engineer",
        "question": "Tell me about a time you fixed a broken data pipeline under pressure.",
        "timeLimit": 120,
    },
    {
        "id": "amz-36",
        "company": "Amazon",
        "role": "data-scientist",
        "question": "Tell me about a time a model you built failed in production.",
        "timeLimit": 120,
    },
    {
        "id": "amz-37",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to manage significant risk in a project.",
        "timeLimit": 120,
    },
    {
        "id": "amz-38",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to mediate a conflict between others.",
        "timeLimit": 120,
    },
    {
        "id": "amz-39",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you dealt with a difficult person at work.",
        "timeLimit": 120,
    },
    {
        "id": "amz-40",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you stepped in to help a co-worker who was struggling to keep up.",
        "timeLimit": 120,
    },
    {
        "id": "amz-41",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to work with a teammate but ultimately couldn't.",
        "timeLimit": 120,
    },
    {
        "id": "amz-42",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you significantly exceeded expectations on a project or task.",
        "timeLimit": 120,
    },
    {
        "id": "amz-43",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you provided important or difficult feedback to someone else.",
        "timeLimit": 120,
    },
    {
        "id": "amz-44",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to work outside your comfort zone and how you gained expertise.",
        "timeLimit": 120,
    },
    {
        "id": "amz-45",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you demonstrated leadership on a cross-functional team.",
        "timeLimit": 120,
    },
    {
        "id": "amz-46",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you questioned the status quo.",
        "timeLimit": 120,
    },
    {
        "id": "amz-47",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you had to dive deep.",
        "timeLimit": 120,
    },
    {
        "id": "amz-48",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you put someone else's interests above your own.",
        "timeLimit": 120,
    },
    {
        "id": "amz-49",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you motivated a team to perform better.",
        "timeLimit": 120,
    },
    {
        "id": "amz-50",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you contributed to hiring or building a team.",
        "timeLimit": 120,
    },
    {
        "id": "amz-51",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you delegated or assigned work to your team on a project.",
        "timeLimit": 120,
    },
    {
        "id": "amz-52",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you taught someone something.",
        "timeLimit": 120,
    },
    {
        "id": "amz-53",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about a time you considered the broader impact of your work on the world.",
        "timeLimit": 120,
    },
    {
        "id": "amz-54",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about the past project or accomplishment you are most proud of.",
        "timeLimit": 120,
    },
    {
        "id": "amz-55",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Tell me about yourself.",
        "timeLimit": 120,
    },
    {
        "id": "amz-56",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Why do you want to switch jobs, and why are you interested in joining Amazon?",
        "timeLimit": 120,
    },
    {
        "id": "amz-57",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "What are your biggest strengths and weaknesses?",
        "timeLimit": 120,
    },
    {
        "id": "amz-58",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "Which Amazon Leadership Principle resonates with you the most, and how have you demonstrated it?",
        "timeLimit": 120,
    },
    {
        "id": "amz-59",
        "company": "Amazon",
        "role": "software-engineer",
        "question": "What is your favorite product or service, and why?",
        "timeLimit": 120,
    },

    # Meta
    {
        "id": "meta-1",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to balance shipping a feature quickly versus paying down technical debt.",
        "timeLimit": 120,
    },
    {
        "id": "meta-2",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to juggle multiple competing priorities. How did you decide what to focus on?",
        "timeLimit": 120,
    },
    {
        "id": "meta-3",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had a disagreement with a teammate or cross-functional partner and how you resolved it.",
        "timeLimit": 120,
    },
    {
        "id": "meta-4",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you made a significant mistake or failed to reach a goal. What did you learn?",
        "timeLimit": 120,
    },
    {
        "id": "meta-5",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you disagreed with your manager or leadership and how you handled it.",
        "timeLimit": 120,
    },
    {
        "id": "meta-6",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you made an unpopular decision and how you secured team buy-in.",
        "timeLimit": 120,
    },
    {
        "id": "meta-7",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to make a critical decision quickly with incomplete information.",
        "timeLimit": 120,
    },
    {
        "id": "meta-8",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you took the initiative to solve a problem outside your core responsibilities.",
        "timeLimit": 120,
    },
    {
        "id": "meta-9",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to troubleshoot a critical production issue, such as a scaling failure or database bottleneck.",
        "timeLimit": 120,
    },
    {
        "id": "meta-10",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to quickly adapt to a significant change in your project or workflow.",
        "timeLimit": 120,
    },
    {
        "id": "meta-11",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you received critical or unpleasant feedback. How did you respond?",
        "timeLimit": 120,
    },
    {
        "id": "meta-12",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about the technical accomplishment you are most proud of and why.",
        "timeLimit": 120,
    },
    {
        "id": "meta-13",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you came up with an innovative solution to a complex problem.",
        "timeLimit": 120,
    },
    {
        "id": "meta-14",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you had to work with a difficult colleague. How did you build trust?",
        "timeLimit": 120,
    },
    {
        "id": "meta-15",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you stepped in to lead a team or project when it wasn't formally your role.",
        "timeLimit": 120,
    },
    {
        "id": "meta-16",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a time you struggled to meet a tight deadline and how you handled it.",
        "timeLimit": 120,
    },
    {
        "id": "meta-17",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Why are you interested in joining Meta, and what are you looking for in your next role?",
        "timeLimit": 120,
    },
    {
        "id": "meta-18",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about a product or feature at Meta you would improve and how.",
        "timeLimit": 120,
    },
    {
        "id": "meta-19",
        "company": "Meta",
        "role": "software-engineer",
        "question": "Tell me about yourself and your background.",
        "timeLimit": 120,
    },
    {
        "id": "meta-20",
        "company": "Meta",
        "role": "data-engineer",
        "question": "Tell me about a time you scaled a data system for growth.",
        "timeLimit": 120,
    },
    {
        "id": "meta-21",
        "company": "Meta",
        "role": "data-analyst",
        "question": "Tell me about a time you found an insight others had missed.",
        "timeLimit": 120,
    },
    {
        "id": "meta-22",
        "company": "Meta",
        "role": "product-manager",
        "question": "Tell me about a time you said no to a feature request.",
        "timeLimit": 120,
    },

    {
        "id": "meta-23",
        "company": "Meta",
        "role": "data-scientist",
        "question": "Tell me about a time you had to explain a complex model to non-technical stakeholders.",
        "timeLimit": 120,
    },

#google!
{
        "id": "goog-1",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you had to balance paying down technical debt with shipping new features.",
        "timeLimit": 120,
    },
    {
        "id": "goog-2",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you faced a difficult technical challenge with a legacy system and how you resolved it.",
        "timeLimit": 120,
    },
    {
        "id": "goog-3",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you had a disagreement with a teammate or cross-functional partner. How did you resolve it?",
        "timeLimit": 120,
    },
    {
        "id": "goog-4",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you failed or made a significant mistake at work. What did you learn?",
        "timeLimit": 120,
    },
    {
        "id": "goog-5",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you had a disagreement with your manager or leadership.",
        "timeLimit": 120,
    },
    {
        "id": "goog-6",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you came up with an innovative solution to a complex problem.",
        "timeLimit": 120,
    },
    {
        "id": "goog-7",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you struggled to meet a tight deadline or had to manage competing priorities.",
        "timeLimit": 120,
    },
    {
        "id": "goog-8",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you received critical or unexpected feedback (such as a lower performance rating). How did you handle it?",
        "timeLimit": 120,
    },
    {
        "id": "goog-9",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you had to adapt to a significant change in how you or your team worked.",
        "timeLimit": 120,
    },
    {
        "id": "goog-10",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you went above and beyond your standard responsibilities on a project.",
        "timeLimit": 120,
    },
    {
        "id": "goog-11",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you went out of your way to mentor or assist a colleague.",
        "timeLimit": 120,
    },
    {
        "id": "goog-12",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you stepped in to lead a team or project when it wasn't formally your role.",
        "timeLimit": 120,
    },
    {
        "id": "goog-13",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you took a calculated risk. What was the outcome?",
        "timeLimit": 120,
    },
    {
        "id": "goog-14",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you made an unpopular decision or had to compromise on a project.",
        "timeLimit": 120,
    },
    {
        "id": "goog-15",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about a time you had to build trust with a new team or a difficult colleague.",
        "timeLimit": 120,
    },
    {
        "id": "goog-16",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about your most significant technical achievement and the impact it had.",
        "timeLimit": 120,
    },
    {
        "id": "goog-17",
        "company": "Google",
        "role": "software-engineer",
        "question": "Why do you want to work at Google, and what are you looking for in your next role?",
        "timeLimit": 120,
    },
    {
        "id": "goog-18",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me about yourself and your background.",
        "timeLimit": 120,
    },
    {
        "id": "goog-19",
        "company": "Google",
        "role": "software-engineer",
        "question": "Tell me something about yourself that isn't on your resume.",
        "timeLimit": 120,
    }
]

@router.get("/questions/")
async def get_questions(
    company: Optional[str] = Query(default=None),
    role: Optional[str] = Query(default=None),
):
    results = QUESTIONS

    if company:
        results = [q for q in results if q["company"].lower() == company.lower()]

    if role:
        results = [q for q in results if q["role"] == role]

    return results
